"""remove max_clicks from links

Revision ID: a36e0a61734c
Revises: dfb52e3cf881
Create Date: 2026-10-06 23:52:05.402154

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a36e0a61734c'
down_revision: Union[str, Sequence[str], None] = 'dfb52e3cf881'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('links', 'max_clicks')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('links', sa.Column('max_clicks', sa.BIGINT(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
