"""create links table

Revision ID: dfb52e3cf881
Revises: 
Create Date: 2026-10-03 23:34:05.987948

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dfb52e3cf881'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('links',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('short_code', sa.Text(), nullable=False),
    sa.Column('destination_url', sa.Text(), nullable=False),
    sa.Column('is_custom_alias', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('click_count', sa.BigInteger(), server_default='0', nullable=False),
    sa.Column('max_clicks', sa.BigInteger(), nullable=True),
    sa.Column('password_hash', sa.Text(), nullable=True),
    sa.Column('campaign_name', sa.Text(), nullable=True),
    sa.CheckConstraint('short_code = lower(short_code)', name='ck_links_short_code_lowercase'),
    sa.CheckConstraint('click_count >= 0',name='ck_links_click_count_nonnegative',),
    sa.CheckConstraint('max_clicks IS NULL OR max_clicks >= 0',name='ck_links_max_clicks_nonnegative',),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('short_code')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('links')
    # ### end Alembic commands ###
